In [1]:
from pyexpat import model
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
import glob
import cv2
import os
import locale
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import concatenate
from tensorflow.keras.metrics import Precision, Recall, BinaryAccuracy
from keras.preprocessing.image import ImageDataGenerator
from sklearn import preprocessing
import locale
from matplotlib import pyplot as plt
import matplotlib.image as mpimg
from IPython.display import display
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from deepforest import CascadeForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
def create_cnn():
    model = Sequential()
    model.add(Conv2D(filters = 96, input_shape = (224, 224, 3),  
                kernel_size = (11, 11), strides = (4, 4),  
                padding = 'valid',kernel_regularizer = 'l2')) 
    model.add(Activation('relu')) 
    # Max-Pooling  
    model.add(MaxPooling2D(pool_size = (2, 2), 
                strides = (2, 2), padding = 'valid')) 
    # Batch Normalisation 
    model.add(BatchNormalization()) 
    
    # 2nd Convolutional Layer 
    model.add(Conv2D(filters = 256, kernel_size = (11, 11),  
                strides = (1, 1), padding = 'valid')) 
    model.add(Activation('relu')) 
    # Max-Pooling 
    model.add(MaxPooling2D(pool_size = (2, 2), strides = (2, 2),  
                padding = 'valid')) 
    # Batch Normalisation 
    model.add(BatchNormalization()) 
    
    # 3rd Convolutional Layer 
    model.add(Conv2D(filters = 384, kernel_size = (3, 3),  
                strides = (1, 1), padding = 'valid')) 
    model.add(Activation('relu')) 
    # Batch Normalisation 
    model.add(BatchNormalization()) 
    
    # 4th Convolutional Layer 
    model.add(Conv2D(filters = 384, kernel_size = (3, 3),  
                strides = (1, 1), padding = 'valid')) 
    model.add(Activation('relu')) 
    # Batch Normalisation 
    model.add(BatchNormalization()) 
    
    # 5th Convolutional Layer 
    model.add(Conv2D(filters = 256, kernel_size = (3, 3),  
                strides = (1, 1), padding = 'valid')) 
    model.add(Activation('relu')) 
    # Max-Pooling 
    model.add(MaxPooling2D(pool_size = (2, 2), strides = (2, 2),  
                padding = 'valid')) 
    # Batch Normalisation 
    model.add(BatchNormalization()) 
    
    # Flattening 
    model.add(Flatten()) 
    
    # 1st Dense Layer 
    model.add(Dropout(0.4)) 
    model.add(Dense(4096,kernel_regularizer='l2')) 
    model.add(Activation('relu') )
    # Add Dropout to prevent overfitting 
    model.add(Dropout(0.4)) 
    # Batch Normalisation 
    model.add(BatchNormalization()) 
    
    # 2nd Dense Layer 
    model.add(Dense(2048,kernel_regularizer='l2') )
    model.add(Activation('relu')) 
    # Add Dropout 
    # Batch Normalisation 
    model.add(BatchNormalization()) 
    model.add(Dense(1,activation = 'sigmoid'))
    return model

In [21]:
gasdata = pd.read_csv("/Users/Eddie/Downloads/Gas Sensors Data - Sheet1 (3) (1).csv")
data_dir = '/Users/Eddie/Downloads/No Gas 4/No Gas'
imagedata = sorted(os.listdir(data_dir))
print(len(imagedata))
X_data = []
for image in imagedata:
        #print(image)
        img = mpimg.imread('/Users/Eddie/Downloads/No Gas 4/No Gas/'+image)
        img.resize(224,224,3)
        img = img/255.0
        X_data.append(img)
images = np.array(X_data)
print(images.shape)

176
(176, 224, 224, 3)


In [22]:
split = train_test_split(gasdata, images, test_size=0.2)
(trainAttrX, testAttrX, trainImagesX, testImagesX) = split
trainy = trainAttrX["Gas"]
testy = testAttrX["Gas"]
trainAttrX = trainAttrX.drop(columns=['Gas'])
testAttrX = testAttrX.drop(columns = ['Gas'])
trainAttrX= (trainAttrX - np.min(trainAttrX)) / (np.max(trainAttrX) - np.min(trainAttrX))
testAttrX = (testAttrX - np.min(testAttrX)) / (np.max(testAttrX) - np.min(testAttrX))
print(trainAttrX.shape)
print(testAttrX.shape)
print(trainy.shape)
print(testy.shape)

# print(testy)
newtesty = []
for value in testy:
    value = float(value)
    newtesty.append(value)
# print(newtesty)
newtrainy = []
for value in trainy:
    value = float(value)
    newtrainy.append(value)


(140, 2)
(36, 2)
(140,)
(36,)


In [28]:
print(newtrainy)
model = create_cnn()
#model.load('/Users/Eddie/Downloads/alexnet')
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 0.00001), loss='binary_crossentropy',metrics = ['acc'])

[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0]


In [30]:
hist = model.fit(trainImagesX,trainy,validation_data=(testImagesX,testy),epochs=150,batch_size = 20)

Epoch 1/150
7/7 [==============================] - 4s 455ms/step - loss: 32.8293 - acc: 0.6571 - val_loss: 32.8264 - val_acc: 0.5556
Epoch 2/150
7/7 [==============================] - 3s 418ms/step - loss: 32.4245 - acc: 0.8643 - val_loss: 32.7793 - val_acc: 0.5556
Epoch 3/150
7/7 [==============================] - 3s 412ms/step - loss: 32.2552 - acc: 0.9357 - val_loss: 32.7268 - val_acc: 0.5556
Epoch 4/150
7/7 [==============================] - 3s 409ms/step - loss: 32.2088 - acc: 0.9286 - val_loss: 32.6708 - val_acc: 0.5556
Epoch 5/150
7/7 [==============================] - 3s 407ms/step - loss: 32.1304 - acc: 0.9429 - val_loss: 32.6130 - val_acc: 0.5556
Epoch 6/150
7/7 [==============================] - 3s 409ms/step - loss: 32.0546 - acc: 0.9500 - val_loss: 32.5539 - val_acc: 0.5556
Epoch 7/150
7/7 [==============================] - 3s 408ms/step - loss: 31.9577 - acc: 0.9429 - val_loss: 32.4944 - val_acc: 0.5556
Epoch 8/150
7/7 [==============================] - 3s 411ms/step - lo

KeyboardInterrupt: 

In [9]:
gasdata = pd.read_csv("/Users/eddie/Downloads/Gas Sensors Data - Sheet1 (3) (1).csv")
result = gasdata['Gas']
gasdata = gasdata.drop(columns=['Gas'])
gasdata= (gasdata - np.min(gasdata)) / (np.max(gasdata) - np.min(gasdata))
images =  sorted(os.listdir("/Users/eddie/Downloads/No Gas 4/No Gas"))
X_dat = []
for image in images:
       #print(image)
       img = mpimg.imread('/Users/eddie/Downloads/No Gas 4/No Gas/'+image)
       img.resize(224,224,3)
       img = img/255.0
       X_dat.append(img)
test_images = np.array(X_dat)

print("gay")
print(test_images.shape)

gay
[[[0.         0.00313725 0.00326028]
  [0.00392157 0.         0.00335256]
  [0.00322953 0.00392157 0.        ]
  ...
  [0.00392157 0.         0.00312188]
  [0.00326028 0.00392157 0.        ]
  [0.00315263 0.00326028 0.00392157]]

 [[0.         0.00313725 0.00326028]
  [0.00392157 0.         0.00312188]
  [0.00326028 0.00392157 0.        ]
  ...
  [0.00392157 0.         0.00342945]
  [0.00321415 0.00392157 0.        ]
  [0.00339869 0.00321415 0.00392157]]

 [[0.         0.00336794 0.00322953]
  [0.00392157 0.         0.00335256]
  [0.00322953 0.00392157 0.        ]
  ...
  [0.00392157 0.         0.00330642]
  [0.00322953 0.00392157 0.        ]
  [0.00330642 0.00322953 0.00392157]]

 ...

 [[0.         0.00298347 0.00329104]
  [0.00392157 0.         0.00290657]
  [0.00330642 0.00392157 0.        ]
  ...
  [0.00392157 0.         0.0030296 ]
  [0.00329104 0.00392157 0.        ]
  [0.00309112 0.00327566 0.00392157]]

 [[0.         0.00313725 0.00327566]
  [0.00392157 0.         0.003183

In [20]:
print(testy)
print(testImagesX[4])
print("gay")
print(test_images[175])

852    1
739    1
594    1
955    1
465    0
      ..
839    1
107    0
277    0
408    0
314    0
Name: Gas, Length: 200, dtype: int64
[[[3.9061899e-03 3.8754325e-03 3.8446751e-03]
  [3.9061899e-03 3.8754325e-03 3.8446751e-03]
  [3.9061899e-03 3.8754325e-03 3.8446751e-03]
  ...
  [3.3525568e-03 3.6755095e-03 0.0000000e+00]
  [3.0911188e-03 3.5217225e-03 0.0000000e+00]
  [2.9680892e-03 3.3986929e-03 0.0000000e+00]]

 [[2.7374087e-03 3.4140716e-03 0.0000000e+00]
  [2.7066513e-03 3.3833142e-03 0.0000000e+00]
  [2.7066513e-03 3.4140716e-03 0.0000000e+00]
  ...
  [3.0603614e-03 3.5217225e-03 0.0000000e+00]
  [3.0911188e-03 3.5217225e-03 0.0000000e+00]
  [3.0911188e-03 3.5217225e-03 0.0000000e+00]]

 [[3.0911188e-03 3.5217225e-03 0.0000000e+00]
  [3.0911188e-03 3.5217225e-03 0.0000000e+00]
  [2.9680892e-03 3.5063438e-03 0.0000000e+00]
  ...
  [3.0296040e-03 3.5063438e-03 0.0000000e+00]
  [3.0142253e-03 3.4448290e-03 0.0000000e+00]
  [3.0911188e-03 3.5217225e-03 0.0000000e+00]]

 ...

 [[2.4

In [41]:

performance = model.predict(testImagesX)
performance.round()
actual = []
for value in performance: 
    #print(value)
    if(value>=0.5):
            actual.append(1)
    else:
            actual.append(0)

print(actual)
acutal = np.array(actual)
actual.append(1)
actual.append(0)
print(result)
testy=np.append(testy,1)
accuracy = accuracy_score(testy,actual)
print('Accuracy: %f' % accuracy)
precision = precision_score(testy, actual)
print('Precision: %f' % precision)
recall = recall_score(testy, actual)
print('Recall: %f' % recall)
f1 = f1_score(testy, actual)
print('F1 score: %f' % f1)

2/2 [==============================] - 0s 35ms/step
[0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]
0      0
1      0
2      0
3      0
4      0
      ..
171    1
172    1
173    1
174    1
175    1
Name: Gas, Length: 176, dtype: int64
Accuracy: 0.736842
Precision: 0.818182
Recall: 0.529412
F1 score: 0.642857
